version: '3'
services:

  api:
    build:
      context: ./api/
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    environment:
      spring_data_mongodb_uri: mongodb://todo:list@mongodb:27017
    networks:
      - mongo
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: list
    networks:
      - mongo
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: todo
      ME_CONFIG_MONGODB_ADMINPASSWORD: list
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo
    depends_on:
      - mongodb
    restart: always

networks:
  mongo: