version: '3'

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      spring_data_mongodb_uri: mongodb://todo:list@mongodb:27017
      spring_redis_host: redis
      cache_ttl_item: 15
      cache_ttl_items: 15
    networks:
      - mongo
      - redis
      - prometheus
    depends_on:
      - mongodb
      - redis

  grafana:
    image: grafana/grafana:8.2.2
    ports:
      - 3000:3000
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: todo
      MONGO_INITDB_ROOT_PASSWORD: list
    networks:
      - mongo
    volumes:
      - ./data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: todo
      ME_CONFIG_MONGODB_ADMINPASSWORD: list
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - mongo
    depends_on:
      - mongodb
    restart: always

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    networks:
      - prometheus
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    # depends_on:
    #   - api

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - redis
    restart: always

networks:
  mongo:
  prometheus:
  redis:
